ES2-UFPI/AgendaTech

- front/Navbar.css
- front/Navbar.js
> Delphino navbar issue#44

- front/ThemeToggle.js
> PR Lógica para inverter cor do tema no arquivo ThemeToggle.js #32

- front/About.css
- front/About.js
> Delphino about issue #41

- front/src/RegisterUser.js
O componente RegisterUser para o registro de novos usuários. O formulário coleta dados básicos, como nome, sobrenome e senha, e envia ao backend para cadastro. A funcionalidade inclui validação básica de campos e tratamento de mensagens de erro ou sucesso.
> Adiciona componente RegisterUser para issue #45

- front/src/RegisterUser.css
Adiciona o arquivo RegisterUser.css para estilizar o formulário de registro de usuários.
> Adiciona estilo ao componente RegisterUser para issue #63

- front/src/Eventos.css
Adiciona estilização para a tela de listagem de eventos.
- Criação do arquivo `Eventos.css` para personalização do layout.
- Aplica estilos ao card de eventos para destaque em hover.
- Define estilos para botões de navegação e textos da listagem.
> Adiciona estilização para tela de listagem de eventos para issue #69

- front/src/Eventos.js
Adiciona a lógica de consumo do endpoint de listagem de eventos.
- Modifica o componente `Eventos.js` para buscar os dados do backend via API.
- Implementa lógica de paginação para exibição de eventos em diferentes páginas.
- Garante tratamento de erros para falhas no carregamento dos eventos.
> Adiciona endpoint de listagem de eventos para issue #68

- front/src/RegisterUser.js
A funcionalidade permite o cadastro de usuários no banco de dados, validando os dados recebidos e retornando uma resposta JSON de sucesso ou erro.
> Implementa endpoint para registrar usuário para issue #62

- front/src/Footer.css
- front/src/Footer.js
Adição de footer(rodapé) da issue #43
> Adição do footer

- front/src/MinhaConta.js
Rota Minha Conta, com informações básicas do usuário logado no sistema.
> Adicionando funcionalidade Minha conta issue #82

- front/src/MinhaConta.css
Estilização necessária da rota Minha Conta.
> Adicionando estilos para Minha conta issue #84

- front/src/LoginUser.css
Estilização necessária da rota login.
> Adicionando estilos para Login issue #87

- front/src/LoginUser.js
> Adicionando funcionalidade Login issue #86

- front/src/UserDropdown.js
> Configurando UserDropdown - issue #33

- front/src/DeadLink.css
Estilização necessária para a página Dead Link.
> Configurando estilos da Página não encontrada issue #80

- front/src/HelpCenter.js
Central de Ajuda com as dúvidas mais comuns que os usuários possam ter, além de endereço e-mail para outras dúvidas.
> Adicionando funcionalidade Central de Ajuda issue #77

- front/src/HelpCenter.css
Estilização necessária para a rota Central de Ajuda.
> Adicionando estilos para Central de Ajuda issue #78

- front/src/UserList.css
Estilização necessária para a rota que lista os usuários cadastrados.
> Configurando estilos de Listar Usuários issue #81

- front/src/UserDropdown.css
Arquivo .css necessário para estilizar o arquivo .js.
> Configurando estilo UserDropdown issue #85

- .github/workflows/ci-cd.yml
adicionei a lógica do github actions para pull requests, e pushs nas branchs dev e master
> Ci cd integração contínua #95

- front/src/Filter.js
> Implementando filtragem de eventos issue #37

- front/src/Filter.css
- front/src/Filter.js
Estilização css para barra de filtragem.
> Filter styles 107

- front/src/Carousel.css
- front/src/Carousel.js
> Adicionando Carrosel e estilização issue #29

- front/src/Carousel.js
Retirei o saiba mais de carrosel, por conta da redundância
> realizando correção da feature carrosel #139

- back/agenda/tests.py
Realizando corretamente o pr desta vez
> Correção dos testes #117

- back/agenda/models.py
> Atualização de models.py para incluir Lista de Desejos. Issue #126

- back/agenda/models.py
- back/agenda/urls.py
Atualização de urls.py da pasta back-agenda #127
> Vival issue#127

- back/agenda/models.py
- back/agenda/urls.py
- back/agenda/views.py
Refatoração do código de views.py
> Vival issue#121

- back/agenda/models.py
- back/agenda/urls.py
- back/agenda/views.py
- back/agenda_backend/urls.py
Atualização de urls.py da pasta principal do back-end #128
> Vival issue#128

- front/src/UserDropdown.css
Alterado visual da lista dos usuários
> alterando o estilo para um  melhor do menu de usuário #137

- front/src/UserDropdown.js
logica da lista de usuários atualizada
> Melhorando o menu de usuário e corrigindo algumas funcionalidades #136

- front/src/RegisterUser.js
Correção de todos os erros da rota para registrar usuários.
> Correção da rota de usuários #135

- front/src/MinhaConta.js
Atualização da rota minha conta. Usada no menu userdropdown.
> Atualização necessária de minha conta #170

- front/package-lock.json
- front/package.json
Sem essa atualização, sempre iria exibir essa mensagem de erro ao carregar a aplicação.
> Atualizando as depedências do front #172

- front/src/About.css
> Correção do css de About #177
